version: "3"
services:
  db:
    image: postgres:latest
    ports:
      - 5000:5000
    environment:
      - POSTGRES_USER=otica_ecommerce_user
      - POSTGRES_PASSWORD=otica_ecommerce_password
      - POSTGRES_DB=otica_ecommerce_db
