version: "3"
services:
  postgres_dev:
    container_name: "postgres-dev"
    image: "postgres:14.1-alpine"
    env_file:
      - ../.env
    ports:
      - "54320:5432"
    volumes:
      - postgres_data:/data/postgres
    restart: unless-stopped
volumes:
  postgres_data:
  # db:
  #   image: postgres:latest
  #   ports:
  #     - 5000:5000
  #   environment:
  #     - POSTGRES_USER=otica_ecommerce_user
  #     - POSTGRES_PASSWORD=otica_ecommerce_password
  #     - POSTGRES_DB=otica_ecommerce_db
